language: rust

rust:
  - nightly
  - beta

script:
  - cargo run --manifest-path demo-rs/Cargo.toml
  - cargo test

matrix:
  include:
    - os: macos
      rust: nightly
    - os: windows
      rust: nightly
      before_script:
        # windows is bad at symlinks
        - rm cmd/src/gen cmd/src/syntax gen/include macro/src/syntax src/gen src/syntax
        - cp -r include gen; cp -r gen cmd/src; cp -r syntax cmd/src; cp -r syntax macro/src; cp -r gen src; cp -r syntax src
    - name: Buck
      rust: nightly
      before_install:
        - sudo apt-get install -y openjdk-8-jdk
        - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        - wget -O buck.deb https://github.com/facebook/buck/releases/download/v2019.10.17.01/buck.2019.10.17.01_all.deb
        - sudo dpkg -i buck.deb
      before_script:
        - cp third-party/Cargo.lock .
        - cargo vendor --versioned-dirs --locked third-party/vendor
      script:
        - buck build :cxx#check --verbose=0
        - buck run demo-rs --verbose=0
        - buck test ... --verbose=0
    - name: Bazel
      rust: nightly
      before_install:
        - wget -O install.sh https://github.com/bazelbuild/bazel/releases/download/2.1.1/bazel-2.1.1-installer-linux-x86_64.sh
        - chmod +x install.sh
        - ./install.sh --user
      before_script:
        - cp third-party/Cargo.lock .
        - cargo vendor --versioned-dirs --locked third-party/vendor
      script:
        - bazel run demo-rs:demo_rs --verbose_failures --noshow_progress
        - bazel test ... --verbose_failures --noshow_progress
  allow_failures:
    - os: windows # https://github.com/dtolnay/cxx/issues/25
