[book]
title = "CXX"
authors = ["David Tolnay"]
description = "Guide for the `cxx` crate, a safe approach to FFI between Rust and C++."

[rust]
edition = "2018"

[build]
build-dir = "build"
create-missing = false

[output.html]
additional-css = ["css/cxx.css"]
cname = "cxx.rs"
git-repository-url = "https://github.com/dtolnay/cxx"
playground = { copyable = false }
print = { enable = false }
